### ISSUE TITLE
Update USGS disclaimer

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-decadal-v2#105]
Add the updated disclaimer
> This software has been approved for release by the U.S. Geological Survey (USGS). Although the software has been subjected to rigorous review, the USGS reserves the right to update the software as needed pursuant to further analysis and review. No warranty, expressed or implied, is made by the USGS or the U.S. Government as to the functionality of the software and related material nor shall the fact of release constitute any such warranty. Furthermore, the software is released on condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from its authorized or unauthorized use.

**Comment by lprivette** [comment]
completed in: https://github.com/USGS-WiM/nawqa-decadal-v2/releases/tag/v4.0.1
