### ISSUE TITLE
Move NAWQA Trends production to S3

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/nawqa-decadal-v2#106]
It is currently on Toad. Is it possible to keep it at this domain https://nawqatrends.wim.usgs.gov/Decadal/ after moving it to S3?

**Comment by aaronstephenson** [comment]
Absolutely. Instead of hosting the code on Toad, we just write a little URL rewrite snippet in the web.config to act as a reverse proxy for the S3 bucket. When do you want this?

**Comment by lprivette** [comment]
Wanna do it when we meet tomorrow?

**Comment by lprivette** [comment]
This is complete
